import { UserProfile } from '@/contexts/UserContext';
import { MarkdownMessage } from './MarkdownMessage';
import { EnterpriseDashboard } from './EnterpriseDashboard';
import { Bot, User as UserIcon } from 'lucide-react';

interface PrintableReportProps {
  messages: any[];
  user: UserProfile | null;
  printMessageIndex?: number | null;
}

export function PrintableReport({ messages, user, printMessageIndex = null }: PrintableReportProps) {
  const reportId = `RPT-${Math.random().toString(36).substr(2, 6).toUpperCase()}-${Date.now().toString().slice(-4)}`;
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const timeStr = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

  let messagesToRender = messages;
  if (typeof printMessageIndex === 'number') {
    messagesToRender = messages.filter((_, idx) => idx === printMessageIndex || idx === printMessageIndex - 1);
  }

  // Generate a mock executive summary based on the first AI message, or use a generic one if empty
  const aiMessages = messagesToRender.filter(m => m.role === 'assistant' && m.content);
  const firstAiContent = aiMessages.length > 0 ? aiMessages[0].content : '';
  const isIncident = firstAiContent.toLowerCase().includes('incident') || firstAiContent.toLowerCase().includes('fail');
  const summary = firstAiContent 
    ? `This report details an investigation via the Industrial Brain AI Copilot. ${isIncident ? 'A critical incident was analyzed.' : 'Routine diagnostics and queries were processed.'} The AI provided contextual insights drawing from the Enterprise GraphRAG system.`
    : "No analytical data was generated in this session.";

  return (
    <div 
      className="hidden print:block w-full bg-white text-black font-sans relative"
      style={{
        WebkitPrintColorAdjust: 'exact',
        printColorAdjust: 'exact'
      }}
    >
      <div className="p-12 pb-24">
      <div className="border-b-2 border-slate-900 pb-6 mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight text-slate-900">FreshFlow Beverages Pvt. Ltd.</h1>
          <p className="text-sm text-slate-500 mt-1 font-medium tracking-widest uppercase">Enterprise Knowledge Intelligence</p>
        </div>
        <div className="text-right">
          <p className="text-xl font-bold text-slate-800">AI Investigation Report</p>
          <p className="text-sm font-mono text-slate-500 mt-1">ID: {reportId}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-8 mb-10">
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-3">Generation Details</h3>
          <div className="space-y-2 text-sm">
            <p><span className="font-semibold w-24 inline-block">Date:</span> {dateStr}</p>
            <p><span className="font-semibold w-24 inline-block">Time:</span> {timeStr}</p>
            <p><span className="font-semibold w-24 inline-block">System:</span> GraphRAG Engine v2.1</p>
          </div>
        </div>
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-3">User Context</h3>
          <div className="space-y-2 text-sm">
            <p><span className="font-semibold w-24 inline-block">Generated By:</span> {user?.name || 'System Auto'}</p>
            <p><span className="font-semibold w-24 inline-block">Employee ID:</span> {user?.employee_id || 'N/A'}</p>
            <p><span className="font-semibold w-24 inline-block">Email:</span> {user?.email || 'N/A'}</p>
            <p><span className="font-semibold w-24 inline-block">Role/Dept:</span> {user?.role || 'Operations'}</p>
          </div>
        </div>
      </div>

      <div className="mb-12">
        <h2 className="text-lg font-bold border-b border-slate-200 pb-2 mb-4">Executive Summary</h2>
        <p className="text-slate-700 leading-relaxed text-sm">
          {summary}
        </p>
      </div>

      <div className="space-y-8 mb-20">
        <h2 className="text-lg font-bold border-b border-slate-200 pb-2 mb-6">Investigation Transcript</h2>
        
        {messagesToRender.map((msg, idx) => {
          if (!msg.content && !msg.dashboard_data) return null;
          
          const isUser = msg.role === 'user';
          
          return (
            <div key={idx} className={`p-5 rounded-xl border ${isUser ? 'bg-blue-50/50 border-blue-100 ml-12' : 'bg-slate-50/50 border-slate-200 mr-12'} break-inside-avoid`}>
              <div className="flex items-center gap-2 mb-3">
                {isUser ? <UserIcon className="w-4 h-4 text-blue-600" /> : <Bot className="w-4 h-4 text-emerald-600" />}
                <span className="font-bold text-sm text-slate-800">{isUser ? user?.name || 'User' : 'AI Copilot'}</span>
                <span className="text-xs text-slate-400 ml-auto">{msg.time}</span>
              </div>
              
              <div className="prose prose-sm prose-slate max-w-none prose-p:leading-relaxed">
                {isUser ? (
                  <p className="whitespace-pre-wrap font-medium">{msg.content}</p>
                ) : (
                  <>
                    {msg.content && <MarkdownMessage content={msg.content} />}
                    
                    {/* Render Dashboard Data if present (charts might not print well, but we can try rendering the dashboard component) */}
                    {msg.dashboard_data && (
                      <div className="mt-4 pt-4 border-t border-slate-200/50">
                        <div className="transform scale-[0.85] origin-top-left">
                           <EnterpriseDashboard data={msg.dashboard_data} />
                        </div>
                      </div>
                    )}
                  </>
                )}
              </div>
            </div>
          );
        })}
      </div>

      </div>
      
      {/* 5. Fixed Footer (repeats on every printed page via standard browser behavior if configured via CSS, but we'll use a fixed footer for print) */}
      <style dangerouslySetInnerHTML={{ __html: `
        @page { size: A4; margin: 0; }
        @media print {
          body { 
            -webkit-print-color-adjust: exact !important; 
            print-color-adjust: exact !important; 
          }
          .print-footer { 
            position: fixed; 
            bottom: 0; 
            left: 0; 
            right: 0; 
            height: 60px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 0 48px;
            background-color: white !important;
            border-top: 1px solid #e2e8f0;
          }
        }
      `}} />
      <div className="print-footer text-xs text-slate-500 font-mono">
        <span>FRESHFLOW BEVERAGES PVT. LTD. — CONFIDENTIAL</span>
        <span>{dateStr} {timeStr}</span>
      </div>
    </div>
  );
}
